# Generated by Django 2.1.2 on 2018-10-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=512)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=6)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=6)),
                ('hw_version', models.IntegerField(default=0)),
                ('fw_version', models.IntegerField(default=0)),
            ],
        ),
    ]
