# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConcentrationSeries(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, concentrationlist: List[float]=None):  # noqa: E501
        """ConcentrationSeries - a model defined in Swagger

        :param concentrationlist: The concentrationlist of this ConcentrationSeries.  # noqa: E501
        :type concentrationlist: List[float]
        """
        self.swagger_types = {
            'concentrationlist': List[float]
        }

        self.attribute_map = {
            'concentrationlist': 'concentrationlist'
        }

        self._concentrationlist = concentrationlist

    @classmethod
    def from_dict(cls, dikt) -> 'ConcentrationSeries':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConcentrationSeries of this ConcentrationSeries.  # noqa: E501
        :rtype: ConcentrationSeries
        """
        return util.deserialize_model(dikt, cls)

    @property
    def concentrationlist(self) -> List[float]:
        """Gets the concentrationlist of this ConcentrationSeries.


        :return: The concentrationlist of this ConcentrationSeries.
        :rtype: List[float]
        """
        return self._concentrationlist

    @concentrationlist.setter
    def concentrationlist(self, concentrationlist: List[float]):
        """Sets the concentrationlist of this ConcentrationSeries.


        :param concentrationlist: The concentrationlist of this ConcentrationSeries.
        :type concentrationlist: List[float]
        """
        if concentrationlist is None:
            raise ValueError("Invalid value for `concentrationlist`, must not be `None`")  # noqa: E501

        self._concentrationlist = concentrationlist
