# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TimeSeries(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, timelist: List[str]=None):  # noqa: E501
        """TimeSeries - a model defined in Swagger

        :param timelist: The timelist of this TimeSeries.  # noqa: E501
        :type timelist: List[str]
        """
        self.swagger_types = {
            'timelist': List[str]
        }

        self.attribute_map = {
            'timelist': 'timelist'
        }

        self._timelist = timelist

    @classmethod
    def from_dict(cls, dikt) -> 'TimeSeries':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TimeSeries of this TimeSeries.  # noqa: E501
        :rtype: TimeSeries
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timelist(self) -> List[str]:
        """Gets the timelist of this TimeSeries.


        :return: The timelist of this TimeSeries.
        :rtype: List[str]
        """
        return self._timelist

    @timelist.setter
    def timelist(self, timelist: List[str]):
        """Sets the timelist of this TimeSeries.


        :param timelist: The timelist of this TimeSeries.
        :type timelist: List[str]
        """
        if timelist is None:
            raise ValueError("Invalid value for `timelist`, must not be `None`")  # noqa: E501

        self._timelist = timelist
